
LIB_CLUSTER = $(STREAMIT_HOME)/library/cluster

CCFLAGS = -O3

# Unsupported target machines
CC_IA64 = ecc
CC_ARM = arm343 #arm-linux-gcc
CCFLAGS_IA64 = -O3
CCFLAGS_ARM = -O3

NAMES = \
	thread0 \
	thread1 \
	thread2 \
	thread3 \


SOURCES = $(NAMES:%=%.cpp)
OBJS = $(NAMES:%=%.o)

OBJS_IA64 = $(NAMES:%=%_ia64.o)
OBJS_ARM = $(NAMES:%=%_arm.o)

all: C4.out

clean:
	rm -f master*.o fusion*.o global*.o thread*.o combined_threads.o C4.out

combined_threads.cpp : master.cpp global.cpp  ${SOURCES}
	@${STREAMIT_HOME}/misc/concat_cluster_threads_cpp.pl $^

C4.out : combined_threads.o 
	$(CXX) $(CCFLAGS) -o $@ $^ -L$(LIB_CLUSTER) -lpthread -lcluster -lstdc++

%.o: %.cpp fusion.h cluster.h global.h
	$(CXX) $(CCFLAGS) -I$(LIB_CLUSTER) -c -o $@ $<


# Unsupported target machines
ia64: C4.out_ia64

arm: C4.out_arm

C4.out_ia64: master_ia64.o $(OBJS_IA64)
	$(CC_IA64) $(CCFLAGS_IA64) -o $@ $^ -L$(LIB_CLUSTER) -lpthread -lcluster_ia64

%_ia64.o: %.cpp fusion.h cluster.h
	$(CC_IA64) $(CCFLAGS_IA64) -I$(LIB_CLUSTER) -c -o $@ $<

C4.out_arm: fusion_arm.o $(OBJS_ARM)
	ar r objects_arm.a $^
	ranlib objects_arm.a
	$(CC_ARM) $(CCFLAGS_ARM) -o $@ objects_arm.a -L$(LIB_CLUSTER) -lstdc++ -lm -lcluster_arm #-lpthread

%_arm.o: %.cpp fusion.h cluster.h
	$(CC_ARM) $(CCFLAGS_ARM) -I$(LIB_CLUSTER) -c -o $@ $<

